// components/HeaderComponent.vue
<template>
  <header class="sticky top-0 z-20 bg-white/80 backdrop-blur-lg border-b border-slate-200">
    <div class="px-4 sm:px-8 h-20 flex justify-between items-center">
      <div class="flex items-center gap-4">
        <button 
          @click="$emit('menuClick')" 
          class="lg:hidden text-slate-600 hover:text-orange-500" 
          aria-label="Open menu"
        >
          <Menu :size="24" />
        </button>
        <h2 class="text-xl sm:text-2xl lg:text-3xl font-bold text-slate-800 whitespace-nowrap">
          {{ title }}
        </h2>
      </div>
      
      <div class="relative" ref="dropdownRef">
        <div 
          @click="isDropdownOpen = !isDropdownOpen" 
          class="flex items-center space-x-2 sm:space-x-4 cursor-pointer group p-2 rounded-lg hover:bg-slate-100 transition-colors"
          role="button"
          aria-haspopup="true"
          :aria-expanded="isDropdownOpen"
        >
          <img 
            :src="`https://i.pravatar.cc/150?u=${user?.email}`" 
            :alt="user?.name || 'User'" 
            class="h-10 w-10 sm:h-11 sm:w-11 rounded-full object-cover ring-2 ring-white"
          />
          <div class="text-right hidden sm:block">
            <p class="font-semibold text-slate-800 text-sm">{{ user?.name || 'User' }}</p>
            <p class="text-xs text-slate-500">Admin</p>
          </div>
          <ChevronDown 
            :size="20" 
            :class="[
              'text-slate-400 group-hover:text-slate-600 transition-transform duration-200',
              isDropdownOpen ? 'rotate-180' : ''
            ]" 
          />
        </div>

        <div 
          v-if="isDropdownOpen"
          class="absolute right-0 mt-2 w-56 origin-top-right bg-white rounded-md shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none z-30 animate-in fade-in-0 zoom-in-95"
        >
          <div class="py-1" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button">
            <div class="px-4 py-3 border-b border-slate-100">
              <p class="text-sm font-semibold text-slate-900 leading-tight">{{ user?.name }}</p>
              <p class="text-xs text-slate-500 truncate mt-0.5">{{ user?.email }}</p>
            </div>
            <div class="py-1">
              <a 
                href="#" 
                @click.prevent="handleGoToSettings" 
                class="flex items-center gap-3 px-4 py-2 text-sm text-slate-700 hover:bg-slate-100 hover:text-slate-900 transition-colors" 
                role="menuitem"
              >
                <Settings :size="16" class="text-slate-500"/>
                <span>Settings</span>
              </a>
              <a 
                href="#" 
                @click.prevent="handleLogout" 
                class="flex items-center gap-3 px-4 py-2 text-sm text-slate-700 hover:bg-red-50 hover:text-red-600 transition-colors" 
                role="menuitem"
              >
                <LogOut :size="16" class="text-slate-500" />
                <span>Logout</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { ChevronDown, Menu, Settings, LogOut } from 'lucide-vue-next'

interface Props {
  title: string
}

interface Emits {
  (e: 'menuClick'): void
}

defineProps<Props>()
defineEmits<Emits>()

const { user, logout } = useAuth()

const isDropdownOpen = ref(false)
const dropdownRef = ref<HTMLDivElement>()

const handleClickOutside = (event: MouseEvent) => {
  if (dropdownRef.value && !dropdownRef.value.contains(event.target as Node)) {
    isDropdownOpen.value = false
  }
}

const handleLogout = (e: Event) => {
  e.preventDefault()
  isDropdownOpen.value = false
  logout()
}

const handleGoToSettings = (e: Event) => {
  e.preventDefault()
  isDropdownOpen.value = false
  // Navigate to settings page
  navigateTo('/settings')
}

onMounted(() => {
  document.addEventListener('mousedown', handleClickOutside)
})

onUnmounted(() => {
  document.removeEventListener('mousedown', handleClickOutside)
})
</script>

// _old_react_files/Header.tsx
import React from 'react';
import { ChevronDown } from 'lucide-react';

interface HeaderProps {
    title: string;
}

export const Header: React.FC<HeaderProps> = ({ title }) => {
    return (
        <header className="sticky top-0 z-30 bg-white/80 backdrop-blur-lg border-b border-slate-200">
            <div className="px-8 h-20 flex justify-between items-center">
                <h2 className="text-3xl font-bold text-slate-800">{title}</h2>
                <div className="flex items-center space-x-4 cursor-pointer group">
                    <img className="h-11 w-11 rounded-full object-cover ring-2 ring-white" src="https://i.pravatar.cc/150?u=moniroy" alt="User" />
                    <div className="text-right hidden sm:block">
                        <p className="font-semibold text-slate-800 text-sm">Moni Roy</p>
                        <p className="text-xs text-slate-500">Admin</p>
                    </div>
                     <ChevronDown size={20} className="text-slate-400 group-hover:text-slate-600 transition-colors" />
                </div>
            </div>
        </header>
    );
};
