// components/NotificationComponent.vue
<template>
  <div 
    :class="[
      'flex items-center gap-3 p-4 rounded-lg shadow-sm border transition-all duration-300',
      type === 'success' ? 'bg-green-50 border-green-200' : 'bg-red-50 border-red-200'
    ]"
  >
    <div 
      :class="[
        'flex-shrink-0 w-6 h-6 rounded-full flex items-center justify-center',
        type === 'success' ? 'bg-green-500' : 'bg-red-500'
      ]"
    >
      <CheckCircle v-if="type === 'success'" :size="16" class="text-white" />
      <XCircle v-else :size="16" class="text-white" />
    </div>
    <p 
      :class="[
        'flex-1 text-sm font-medium',
        type === 'success' ? 'text-green-800' : 'text-red-800'
      ]"
    >
      {{ message }}
    </p>
    <button
      @click="$emit('close')"
      class="flex-shrink-0 text-slate-400 hover:text-slate-600"
    >
      <X :size="20" />
    </button>
  </div>
</template>

<script setup lang="ts">
import { CheckCircle, XCircle, X } from 'lucide-vue-next'

interface Props {
  message: string
  type: 'success' | 'error'
}

interface Emits {
  (e: 'close'): void
}

defineProps<Props>()
defineEmits<Emits>()
</script>

// components/ui/notification/Notification.tsx
import React from 'react';
import { CheckCircle, XCircle, X } from 'lucide-react';

interface NotificationProps {
    message: string;
    type: 'success' | 'error';
    onClose: () => void;
}

export const Notification: React.FC<NotificationProps> = ({ message, type, onClose }) => {
    const isSuccess = type === 'success';
    
    const baseClasses = "max-w-md w-full bg-white shadow-2xl rounded-lg pointer-events-auto ring-1 ring-black ring-opacity-5 overflow-hidden";
    const iconColor = isSuccess ? 'text-green-500' : 'text-red-500';
    const textColor = 'text-slate-800';
    const closeButtonHover = isSuccess ? 'hover:bg-green-100' : 'hover:bg-red-100';

    return (
        <div className={baseClasses}>
            <div className="p-4">
                <div className="flex items-start">
                    <div className="flex-shrink-0">
                        {isSuccess ? 
                            <CheckCircle className={iconColor} aria-hidden="true" /> : 
                            <XCircle className={iconColor} aria-hidden="true" />}
                    </div>
                    <div className={`ml-3 w-0 flex-1 pt-0.5`}>
                        <p className={`text-sm font-semibold ${textColor}`}>{isSuccess ? 'Successfully!' : 'Error!'}</p>
                        <p className={`mt-1 text-sm text-slate-500`}>{message}</p>
                    </div>
                    <div className="ml-4 flex-shrink-0 flex">
                        <button 
                            onClick={onClose} 
                            className={`inline-flex rounded-md p-1.5 text-slate-400 ${closeButtonHover} focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-400 transition-colors`}
                        >
                            <span className="sr-only">Close</span>
                            <X size={20} />
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};
