// _old_react_files/Sidebar.tsx
import React, { useState } from 'react';
import { ChevronDown, LayoutDashboard, Settings, LogOut, Presentation, Megaphone } from 'lucide-react';
import { SlideCategory } from '../types';

interface NavItemProps {
    icon: React.ReactNode;
    text: string | React.ReactNode;
    hasSubmenu?: boolean;
    isSubmenuOpen?: boolean;
    onClick: () => void;
    children?: React.ReactNode;
    active?: boolean;
}

const NavItem: React.FC<NavItemProps> = ({ icon, text, hasSubmenu = false, isSubmenuOpen = false, onClick, children, active = false }) => (
    <div>
        <a 
            href="#" 
            onClick={(e) => { e.preventDefault(); onClick(); }} 
            className={`flex items-center p-3 my-1.5 rounded-lg transition-all duration-200 group ${active ? 'bg-orange-500 text-white shadow-lg shadow-orange-500/30' : 'text-slate-600 hover:bg-slate-100'}`}
        >
            <div className={active ? 'text-white' : 'text-slate-500 group-hover:text-orange-500'}>{icon}</div>
            <span className="ml-4 flex-1 text-sm font-semibold whitespace-nowrap">{text}</span>
            {hasSubmenu && <ChevronDown size={18} className={`transition-transform duration-200 ${isSubmenuOpen ? 'rotate-180' : ''}`} />}
        </a>
        {hasSubmenu && isSubmenuOpen && (
            <ul className="pl-12 pr-2 py-1 space-y-1">{children}</ul>
        )}
    </div>
);

interface SubNavItemProps {
    text: string;
    onClick: () => void;
    active: boolean;
}

const SubNavItem: React.FC<SubNavItemProps> = ({ text, onClick, active }) => (
    <li>
        <a 
            href="#" 
            onClick={(e) => { e.preventDefault(); onClick(); }} 
            className={`block p-2 text-sm rounded-md transition-colors ${active ? 'font-bold text-orange-600' : 'text-slate-500 hover:text-orange-500 font-medium'}`}
        >
            {text}
        </a>
    </li>
);

interface SidebarProps {
    activeView: SlideCategory;
    setActiveView: (view: SlideCategory) => void;
}

export const Sidebar: React.FC<SidebarProps> = ({ activeView, setActiveView }) => {
    const [openMenus, setOpenMenus] = useState({ 
        mobile: activeView.startsWith('mobile'), 
        website: activeView.startsWith('website') 
    });

    const toggleMenu = (menu: 'mobile' | 'website') => {
        setOpenMenus(prev => ({ ...prev, [menu]: !prev[menu] }));
    };

    return (
        <aside className="w-72 bg-white border-r border-slate-200 flex flex-col h-screen fixed">
            <div className="p-6 border-b border-slate-200 flex items-center justify-center h-20">
                <h1 className="text-3xl font-extrabold text-orange-500">Vireak Buntham</h1>
            </div>
            <nav className="flex-1 p-4 overflow-y-auto">
                <NavItem 
                    icon={<LayoutDashboard size={22} />}
                    text="Mobile"
                    hasSubmenu
                    isSubmenuOpen={openMenus.mobile}
                    onClick={() => toggleMenu('mobile')}
                    active={activeView.startsWith('mobile')}
                >
                    <SubNavItem text="Slide Show" active={activeView === 'mobile-slideshow'} onClick={() => setActiveView('mobile-slideshow')} />
                    <SubNavItem text="Advertising" active={activeView === 'mobile-advertising'} onClick={() => setActiveView('mobile-advertising')} />
                </NavItem>
                <NavItem
                    icon={<Presentation size={22} />}
                    text="Website"
                    hasSubmenu
                    isSubmenuOpen={openMenus.website}
                    onClick={() => toggleMenu('website')}
                    active={activeView.startsWith('website')}
                >
                    <SubNavItem text="Slide Show" active={activeView === 'website-slideshow'} onClick={() => setActiveView('website-slideshow')} />
                    <SubNavItem text="Advertising" active={activeView === 'website-advertising'} onClick={() => setActiveView('website-advertising')} />
                </NavItem>
                <NavItem icon={<Settings size={22} />} text="Settings" onClick={() => {}} />
            </nav>
            <div className="p-4 border-t border-slate-200">
                <NavItem 
                    icon={<LogOut size={22} />} 
                    text={<span className="text-red-500 group-hover:text-red-600">Logout</span>} 
                    onClick={() => {}}
                    active={false} // Ensure logout never gets the primary active style
                />
            </div>
        </aside>
    );
};

// components/layout/Sidebar.vue
<template>
  <aside class="w-72 bg-white border-r border-slate-200 flex flex-col h-screen fixed z-40 transition-transform duration-300 ease-in-out lg:translate-x-0" 
         :class="{ 'translate-x-0': isSidebarOpen, '-translate-x-full': !isSidebarOpen }">
    
    <!-- Header -->
    <div class="p-6 border-b border-slate-200 flex items-center justify-between h-20">
      <h1 class="text-3xl font-extrabold text-orange-500">Vireak Buntham</h1>
      <button 
        @click="$emit('closeSidebar')"
        class="lg:hidden text-slate-400 hover:text-slate-700 p-1 rounded-full transition-colors"
      >
        <X :size="24" />
      </button>
    </div>
    
    <!-- Navigation -->
    <nav class="flex-1 p-4 overflow-y-auto">
      <NavItem 
        :icon="LayoutDashboard"
        text="Mobile"
        :hasSubmenu="true"
        :isSubmenuOpen="openMenus.mobile"
        :active="activeCategory.startsWith('mobile')"
        @click="toggleMenu('mobile')"
      >
        <SubNavItem 
          text="Slide Show" 
          :active="activeCategory === 'mobile-slideshow'" 
          @click="$emit('categoryChange', 'mobile-slideshow')" 
        />
        <SubNavItem 
          text="Advertising" 
          :active="activeCategory === 'mobile-advertising'" 
          @click="$emit('categoryChange', 'mobile-advertising')" 
        />
      </NavItem>
      
      <NavItem
        :icon="Presentation"
        text="Website"
        :hasSubmenu="true"
        :isSubmenuOpen="openMenus.website"
        :active="activeCategory.startsWith('website')"
        @click="toggleMenu('website')"
      >
        <SubNavItem 
          text="Slide Show" 
          :active="activeCategory === 'website-slideshow'" 
          @click="$emit('categoryChange', 'website-slideshow')" 
        />
        <SubNavItem 
          text="Advertising" 
          :active="activeCategory === 'website-advertising'" 
          @click="$emit('categoryChange', 'website-advertising')" 
        />
      </NavItem>
      
      <NavItem 
        :icon="Settings" 
        text="Settings" 
        @click="() => {}" 
      />
    </nav>
    
    <!-- Footer -->
    <div class="p-4 border-t border-slate-200">
      <NavItem 
        :icon="LogOut"
        :active="false"
        @click="handleLogout"
      >
        <template #text>
          <span class="text-red-500 group-hover:text-red-600">Logout</span>
        </template>
      </NavItem>
    </div>
  </aside>
</template>

<script setup lang="ts">
import { LayoutDashboard, Presentation, Settings, LogOut, X } from 'lucide-vue-next'
import type { SlideCategory } from '~/types'

// Props
interface Props {
  activeCategory: SlideCategory
  isSidebarOpen: boolean
}

const props = defineProps<Props>()

// Emits
const emit = defineEmits<{
  categoryChange: [category: SlideCategory]
  closeSidebar: []
}>()

// State
const openMenus = ref({ 
  mobile: props.activeCategory.startsWith('mobile'), 
  website: props.activeCategory.startsWith('website') 
})

// Watch for category changes to update menu states
watch(() => props.activeCategory, (newCategory) => {
  openMenus.value = {
    mobile: newCategory.startsWith('mobile'),
    website: newCategory.startsWith('website')
  }
})

// Methods
const toggleMenu = (menu: 'mobile' | 'website') => {
  openMenus.value[menu] = !openMenus.value[menu]
}

const { logout } = useAuth()
const handleLogout = () => {
  logout()
}
</script>
