// _old_react_files/RegisterForm.tsx
import React, { useState } from 'react';
import { useAuth } from '../../store/AuthContext';
import { User, Mail, Lock } from 'lucide-react';

interface RegisterFormProps {
    navigateToLogin: () => void;
}

export const RegisterForm: React.FC<RegisterFormProps> = ({ navigateToLogin }) => {
    const { register } = useAuth();
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [error, setError] = useState('');
    const [isLoading, setIsLoading] = useState(false);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (password.length < 6) {
            setError('Password must be at least 6 characters long.');
            return;
        }
        setError('');
        setIsLoading(true);
        try {
            await register(name, email, password);
        } catch (err) {
            setError(err instanceof Error ? err.message : 'An unknown error occurred.');
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <form onSubmit={handleSubmit} className="space-y-6">
            {error && <p className="bg-red-100 border border-red-300 text-red-700 text-sm rounded-lg p-3 text-center">{error}</p>}
            <div className="relative">
                <label htmlFor="name" className="sr-only">Full Name</label>
                <User className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
                <input
                    id="name"
                    type="text"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    placeholder="Full Name"
                    className="w-full pl-10 pr-4 py-3 bg-slate-50 border border-slate-200 rounded-lg placeholder:text-slate-400 text-slate-800 focus:bg-white focus:border-orange-500 focus:ring-2 focus:ring-orange-500/20 transition-all duration-200 outline-none"
                    required
                />
            </div>
            <div className="relative">
                <label htmlFor="email-reg" className="sr-only">Email</label>
                <Mail className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
                <input
                    id="email-reg"
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    placeholder="Email address"
                    className="w-full pl-10 pr-4 py-3 bg-slate-50 border border-slate-200 rounded-lg placeholder:text-slate-400 text-slate-800 focus:bg-white focus:border-orange-500 focus:ring-2 focus:ring-orange-500/20 transition-all duration-200 outline-none"
                    required
                />
            </div>
            <div className="relative">
                <label htmlFor="password-reg" className="sr-only">Password</label>
                <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
                <input
                    id="password-reg"
                    type="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    placeholder="Password"
                    className="w-full pl-10 pr-4 py-3 bg-slate-50 border border-slate-200 rounded-lg placeholder:text-slate-400 text-slate-800 focus:bg-white focus:border-orange-500 focus:ring-2 focus:ring-orange-500/20 transition-all duration-200 outline-none"
                    required
                />
            </div>
            <button
                type="submit"
                disabled={isLoading}
                className="w-full flex justify-center items-center px-6 py-3.5 bg-orange-500 text-white font-bold rounded-lg hover:bg-orange-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-orange-500 transition-all duration-200 disabled:bg-orange-300 disabled:cursor-not-allowed"
            >
                {isLoading ? 'Creating account...' : 'Create Account'}
            </button>
            <p className="text-center text-sm text-slate-500">
                Already have an account?{' '}
                <button type="button" onClick={navigateToLogin} className="font-semibold text-orange-600 hover:underline">
                    Sign in
                </button>
            </p>
        </form>
    );
};

// components/auth/RegisterForm.vue
<template>
  <form @submit.prevent="handleSubmit" class="space-y-6">
    <div v-if="error" class="bg-red-100 border border-red-300 text-red-700 text-sm rounded-lg p-3 text-center">
      {{ error }}
    </div>
    
    <div class="relative">
      <label for="name" class="sr-only">Full Name</label>
      <User class="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
      <input
        id="name"
        v-model="name"
        type="text"
        placeholder="Full Name"
        class="w-full pl-10 pr-4 py-3 bg-slate-50 border border-slate-200 rounded-lg placeholder:text-slate-400 text-slate-800 focus:bg-white focus:border-orange-500 focus:ring-2 focus:ring-orange-500/20 transition-all duration-200 outline-none"
        required
      />
    </div>
    
    <div class="relative">
      <label for="email-reg" class="sr-only">Email</label>
      <Mail class="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
      <input
        id="email-reg"
        v-model="email"
        type="email"
        placeholder="Email address"
        class="w-full pl-10 pr-4 py-3 bg-slate-50 border border-slate-200 rounded-lg placeholder:text-slate-400 text-slate-800 focus:bg-white focus:border-orange-500 focus:ring-2 focus:ring-orange-500/20 transition-all duration-200 outline-none"
        required
      />
    </div>
    
    <div class="relative">
      <label for="password-reg" class="sr-only">Password</label>
      <Lock class="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
      <input
        id="password-reg"
        v-model="password"
        type="password"
        placeholder="Password"
        class="w-full pl-10 pr-4 py-3 bg-slate-50 border border-slate-200 rounded-lg placeholder:text-slate-400 text-slate-800 focus:bg-white focus:border-orange-500 focus:ring-2 focus:ring-orange-500/20 transition-all duration-200 outline-none"
        required
      />
    </div>
    
    <button
      type="submit"
      :disabled="isLoading"
      class="w-full flex justify-center items-center px-6 py-3.5 bg-orange-500 text-white font-bold rounded-lg hover:bg-orange-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-orange-500 transition-all duration-200 disabled:bg-orange-300 disabled:cursor-not-allowed"
    >
      {{ isLoading ? 'Creating account...' : 'Create Account' }}
    </button>
    
    <p class="text-center text-sm text-slate-500">
      Already have an account?
      <button 
        type="button" 
        @click="$emit('navigate-to-login')" 
        class="font-semibold text-orange-600 hover:underline"
      >
        Sign in
      </button>
    </p>
  </form>
</template>

<script setup lang="ts">
import { User, Mail, Lock } from 'lucide-vue-next'

// Emits
defineEmits<{
  'navigate-to-login': []
}>()

// Composables
const { register } = useAuth()

// State
const name = ref('')
const email = ref('')
const password = ref('')
const error = ref('')
const isLoading = ref(false)

// Methods
const handleSubmit = async () => {
  if (password.value.length < 6) {
    error.value = 'Password must be at least 6 characters long.'
    return
  }
  
  error.value = ''
  isLoading.value = true
  
  try {
    await register(name.value, email.value, password.value)
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'An unknown error occurred.'
  } finally {
    isLoading.value = false
  }
}
</script>
